import './globals.css';
import { Inter } from 'next/font/google';
import {StyledRegistry, Providers} from 'ui';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="gs">
      <body className={inter.className}>
        <Providers>
          <StyledRegistry>{children}</StyledRegistry>
        </Providers>
      </body>
    </html>
  );
}
